name: SimpleKits
version: 1.0
api-version: '1.13'
main: local.simplekits.SimpleKitsPlugin
description: GKits, gkit gems, and mystery spawners
authors: [Dev]
softdepend: [FactionEnchants, SimpleCrates, SimpleEconomy]

commands:
  gkits:
    description: Open gkits GUI
    aliases: [kitgui]
  kits:
    description: Open rank kits GUI
  gkit:
    description: Claim a specific gkit
    usage: /gkit <kitname>
  gkitcreate:
    description: Create a custom gkit via GUI
    usage: /gkitcreate [name]
    permission: simplekits.admin
  gkitedit:
    description: Edit an existing gkit via GUI
    usage: /gkitedit <name>
    permission: simplekits.admin
  gkitroll:
    description: Roll and receive a gkit instantly
    usage: /gkitroll <name>
    permission: simplekits.gkitroll
  gkitgem:
    description: Give gkit gems
    usage: /gkitgem give <player> <kit|random> [amount]
    permission: simplekits.admin
  gkitlock:
    description: Lock gkits for players
    usage: /gkitlock <all|player <name>>
    permission: simplekits.admin
  gkitunlock:
    description: Unlock gkits for players (admin)
    usage: /gkitunlock <player <name> <kit|all>|all <kit>>
    permission: simplekits.admin
  gkitpiece:
    description: Give a random gear piece from a gkit to a player (admin/envoy)
    usage: /gkitpiece give <player> <kit>
    permission: simplekits.admin
  spawner:
    description: Get a mystery spawner or give one to a player.
    usage: /spawner [open] | /spawner give <player> <mobtype|mystery>
  kit:
    description: Claim a specific kit or create one
    usage: /kit <name>|create [name]
  kitcreate:
    description: Create a custom kit via GUI
    usage: /kitcreate [name]
    permission: simplekits.admin
  kitdelete:
    description: Delete a kit or gkit
    usage: /kitdelete <name>|kit <name>|gkit <name>
    permission: simplekits.admin
  gkitdelete:
    description: Delete a gkit
    usage: /gkitdelete <name>|gkit <name>
    permission: simplekits.admin

permissions:
  simplekits.admin:
    description: Admin access to SimpleKits management commands
    default: op
  simplekits.gkitroll:
    description: Allows using /gkitroll
    default: false
